### PR TITLE
Revise documentation of `mul_rev_to_pair`

### PR DESCRIPTION
**Pull request by unageek**
I still don't understand why the decorated version of the function returns decorations other than `trv` or `ill`.

### CODE REVIEW

**Comment by Chris00** [comment]
It doesn't.  In section 12.12.3, it is said

> There shall be a decorated version where each of 𝐛, 𝐜, 𝐮 and 𝐯 is
> of the corresponding decorated type. If either input is NaI then
> both outputs are NaI. Otherwise, if 𝐛 and 𝐜 are nonempty and
> 0 ∉ 𝐛, then 𝐮 is the same as the result of normal division 𝐜/𝐛
> and shall be decorated the same way; while 𝐯 is empty and shall
> be decorated `trv`.  In all other cases each output, empty or
> not, shall be decorated `trv`.

Thus, when the result is  𝐜/𝐛, the decoration can be different.

**Comment by unageek** [comment]
Sorry, I should have said “*can return* decorations other than `trv` or `ill`.”

>when the result is  𝐜/𝐛, the decoration can be different.

This does not align with other decorated reverse-mode functions, which always return NaI or an interval decorated with `trv`.

[At this moment](https://grouper.ieee.org/groups/1788/email/msg06309.html) (see the attachment div2pair.pdf on the page), mulRevPair was not supposed to have a (non-trivially) decorated version. At some point after this, the decorated version was introduced, but I couldn't find corresponding messages in the mailing list just by Googling.

**Comment by Chris00** [comment]
I agree. you need $0 \in \operatorname{int} \boldsymbol{y}$ for the result to be made of 2 intervals.  I rewrote the comments too fast, sorry.  And one probably have to say that it then “returns `[z1, z2]` where `z1` (resp. `z2`) is an enclosure of $\boldsymbol{z_1}$ (resp. $\boldsymbol{z_2}$)” (not sure one can escape the heaviness of this formulation).

BTW, if you write $/_{\text{set}}$, there is no need to add a prime IMHO (the label `set` already disambiguate it from the “standard” division).

**Comment by unageek** [comment]
>if you write $/_{\text{set}}$, there is no need to add a prime

I used $_\mathrm{set}$ to express that the operator produces a set that may not be an interval, and $^\prime$ to express that the division is the relational one. So I would like to keep both.

**Comment by Chris00** [comment]
I understand your point of view but the second one can be written as $𝒙 \mathbin{/_{\text{set}}} 𝒚 = \lbrace z ∈ ℝ ∣ ∃y ∈ 𝒚 ∖ \lbrace0\rbrace : zy ∈ 𝒙\rbrace$ blurring the distinction with the "relational one".  IMHO, the fact that ℝ is returned when $0 \in 𝒙 \land 0 \in 𝒚$ is not the main point of this operator (for the Newton method, it is actually a case one has to circumvent) but the fact that the convex hull of the result is not taken whenever  $0 \notin 𝒙 \land 0 \in 𝒚$.  It's OK to me to keep the $^\prime$ as you mention both definitions and indeed need a way to distinguish them.

**Comment by unageek** [comment]
>second one can be written as $𝒙 \mathbin{/_{\text{set}}} 𝒚 = \lbrace z ∈ ℝ ∣ ∃y ∈ 𝒚 ∖ \lbrace0\rbrace : zy ∈ 𝒙\rbrace$

Thank you for pointing this out! That makes things much clearer.

As you say, the case where $𝒙 = 𝒚 = \\{0\\}$ may not have much practical use, but I think users want to know the exact difference between division and reverse multiplication. I don't want to complicate the notation, of course.

**Pull request merged**
