### PR TITLE
Fix Clippy warnings

### PR DESCRIPTION
**Pull request by Chris00**
Fix Clippy warnings — as agreed in https://github.com/unageek/inari/pull/100#issuecomment-2254186472

### CODE REVIEW

**Comment by unageek** [comment]
Thank you for the PR!

Could you fix src/simd/aarch64.rs as well? I'll test it locally before merging.

**Comment by Chris00** [comment]
Maybe a test for aarch should be added to the CI?

**Comment by Chris00** [comment]
P.S. Once this is merged, I may also open another PR to add `Unpin` for (Dec)Interval.

**Comment by unageek** [comment]
> Maybe a test for aarch should be added to the CI?

Yes, I'll add the macos-latest runner, which runs on Apple M1.

> P.S. Once this is merged, I may also open another PR to add `Unpin` for (Dec)Interval.

That sounds good! Please go ahead.

**Pull request merged**
